name: API Pipeline

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * *'  # runs daily at 8am UTC

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install papermill

      - name: Run API Notebook
        run: papermill notebooks/iOS_API_Extract_Load_Raw.ipynb notebooks/output_api.ipynb
